site_name: Documentacion BasketTCG
theme:
  name: material
  language: es
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
      primary: custom
      accent: custom
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro
      primary: custom
      accent: custom
extra_css:
  - stylesheets/extra.css
